# docker compose  --- 노출포트 16379 로 함
version: '3'
services:
  redis:
    container_name: redis
    image: 'redis:7'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=
    ports:
      - '16379:6379'
    restart: always
    command: redis-server --appendonly yes --appendfsync everysec

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=deleveryETL!
    ports:
      - 15432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    user: "${USER_ID}:${GROUP_ID}"


